# Generated by Django 4.1.5 on 2023-02-01 22:30

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('info', models.TextField(max_length=300)),
                ('price', models.FloatField(validators=[product.models.digit_validate])),
                ('qty', models.IntegerField(validators=[product.models.digit_validate])),
                ('image', models.ImageField(upload_to='img/product')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.category')),
            ],
        ),
    ]
