# Generated by Django 4.1.5 on 2023-02-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='img/category/product5', upload_to='img/category'),
        ),
    ]
