# Generated by Django 4.1.5 on 2023-02-01 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_promotion_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InProcessPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_process', models.BooleanField(default=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
                ('promotion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.promotiontype')),
            ],
        ),
    ]
