# Generated by Django 4.1.5 on 2023-02-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
