# Generated by Django 4.1.5 on 2023-02-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_category_options_category_level_category_lft_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_cat',
            new_name='parent',
        ),
    ]
