# Generated by Django 4.1.5 on 2023-02-08 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_category_level_remove_category_lft_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
