# Generated by Django 4.1.5 on 2023-02-09 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_product_id_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inprocesspromo',
            name='product_id',
        ),
        migrations.AddField(
            model_name='inprocesspromo',
            name='product',
            field=models.ForeignKey(default='small table', on_delete=django.db.models.deletion.DO_NOTHING, to='product.product'),
            preserve_default=False,
        ),
    ]
