# Generated by Django 4.1.5 on 2023-02-01 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('09\\d{9}', 'Your mobile number must start with 09')]),
        ),
    ]
