# Generated by Django 4.1.5 on 2023-02-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_optcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optcode',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
