# Generated by Django 4.1.5 on 2023-02-09 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_optcode_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OptCode',
            new_name='OtpCode',
        ),
    ]
