# Generated by Django 4.1.5 on 2023-02-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_address_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='img/user/avatar7.png', upload_to='img/user/'),
        ),
    ]
