# Generated by Django 4.1.5 on 2023-02-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payaccount',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='PayAccount',
        ),
    ]
