# Generated by Django 4.1.5 on 2023-02-01 22:04

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_address_is_default_payaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payaccount',
            name='account_number',
            field=models.BigIntegerField(validators=[user.models.account_number_validate]),
        ),
        migrations.AlterField(
            model_name='payaccount',
            name='expiry_date',
            field=models.DateField(validators=[user.models.expiry_date_validate]),
        ),
    ]
