# Generated by Django 4.1.5 on 2023-02-16 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iranian_cities.fields


class Migration(migrations.Migration):

    dependencies = [
        ('iranian_cities', '0004_remove_abadi_shhahr'),
        ('user', '0007_remove_payaccount_user_id_delete_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=9)),
                ('detail', models.TextField(max_length=300)),
                ('is_default', models.BooleanField(default=False)),
                ('ostan', iranian_cities.fields.OstanField(default=8, on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.ostan')),
                ('shahrestan', iranian_cities.fields.ShahrestanField(default=126, on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.shahrestan')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
