# Generated by Django 4.1.5 on 2023-02-16 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.BigIntegerField(validators=[user.models.account_number_validate])),
                ('expiry_date', models.DateField(validators=[user.models.expiry_date_validate])),
                ('is_default', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
