# Generated by Django 4.1.5 on 2023-02-04 16:06

from django.db import migrations
import django.db.models.deletion
import iranian_cities.fields


class Migration(migrations.Migration):

    dependencies = [
        ('iranian_cities', '0004_remove_abadi_shhahr'),
        ('user', '0009_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city_id',
        ),
        migrations.AddField(
            model_name='address',
            name='ostan',
            field=iranian_cities.fields.OstanField(default=1, on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.ostan'),
        ),
        migrations.AddField(
            model_name='address',
            name='shahr',
            field=iranian_cities.fields.ShahrField(default=1, on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.shahr'),
        ),
        migrations.AddField(
            model_name='address',
            name='shahrestan',
            field=iranian_cities.fields.ShahrestanField(default=1, on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.shahrestan'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
