# Generated by Django 4.1.5 on 2023-02-04 16:09

from django.db import migrations
import django.db.models.deletion
import iranian_cities.fields


class Migration(migrations.Migration):

    dependencies = [
        ('iranian_cities', '0004_remove_abadi_shhahr'),
        ('user', '0010_remove_address_city_id_address_ostan_address_shahr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='shahr',
        ),
        migrations.AlterField(
            model_name='address',
            name='ostan',
            field=iranian_cities.fields.OstanField(default=8, on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.ostan'),
        ),
        migrations.AlterField(
            model_name='address',
            name='shahrestan',
            field=iranian_cities.fields.ShahrestanField(default=126, on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.shahrestan'),
        ),
    ]
