# Generated by Django 4.1.5 on 2023-02-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_shippingmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('verification', 'verification'), ('equiping', 'equiping'), ('sending', 'sending'), ('delivered', 'delivered')], max_length=20)),
            ],
        ),
    ]
