# Generated by Django 4.1.5 on 2023-02-14 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_inprocesspromo_product_id_and_more'),
        ('order', '0003_remove_cartitem_product_id_cartitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='order.usercart'),
        ),
        migrations.AlterField(
            model_name='cartdetail',
            name='promotion_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='promotion', to='product.promotion'),
        ),
        migrations.AlterField(
            model_name='cartdetail',
            name='shipping_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping', to='order.shippingmethod'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.usercart'),
        ),
    ]
