# Generated by Django 4.1.5 on 2023-02-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_cartdetail_cart_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdetail',
            name='entry',
        ),
        migrations.AddField(
            model_name='usercart',
            name='entry',
            field=models.BooleanField(default=False),
        ),
    ]
