# Generated by Django 4.1.5 on 2023-02-04 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdetail',
            name='pay_account_id',
        ),
    ]
