# Generated by Django 4.1.5 on 2023-02-15 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_cartdetail_entry_usercart_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetail',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='order.cartstatus'),
        ),
    ]
