# Generated by Django 4.1.5 on 2023-02-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_cartdetail_pay_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartstatus',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
